# docker-compose.yml

version: '3'

services:
  fastapi_app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mongo
    env_file:
      - .env

  db:
    container_name: PostGres
    image: postgres:latest
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  flyway:
    image: flyway/flyway:9.22.3
    command: -url=jdbc:postgresql://db:5432/${POSTGRES_DB} -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} -locations=filesystem:/flyway/sql -outOfOrder=true migrate
    volumes:
      - ./app/sqlscripts:/flyway/sql
    depends_on:
      - db
    

  mongo:
    image: mongo
    container_name: MongoDB
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongouser"
      MONGO_INITDB_ROOT_PASSWORD: "mongopass"
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017


volumes:
  mongo-data:
  postgres-data:
